### ISSUE TITLE
x509: certificate signed by unknown authority 

### ISSUE THREAD

**Issue by JRDevo** [JackDallas/Premiumizearr#15]
Hello,

Firstly thanks for this app, there is a gap in my app stack and if this app works as expected it will be a happy replacement for SABnzbd and premiumizer. 

I was trying to build a **docker image** for this app and have had some success but today this keeps popping up:

ERRO[0000] Error getting folders: Get "https://www.premiumize.me/api/folder/list?apikey=111111111111111": x509: certificate signed by unknown authority 
FATA[0000] Cannot read folders from premiumize.me, exiting!

I noticed a similar behavior in Zorin OS. Error log:

[31mERRO[0m[0000] Directory created in blackhole /home/dlbots/Downloads/torrents/tv ignoring (Warning premiumizearrzed does not look in subfolders!) 
[31mERRO[0m[0000] Directory created in blackhole /home/dlbots/Downloads/torrents/default ignoring (Warning premiumizearrzed does not look in subfolders!) 
[31mERRO[0m[0000] Directory created in blackhole /home/dlbots/Downloads/torrents/movie ignoring (Warning premiumizearrzed does not look in subfolders!) 
[31mERRO[0m[0000] Error with initial directory scan open /home/dlbots/Downloads/torrents/: no such file or directory 
ERRO[0000] Error getting folders: Get "https://www.premiumize.me/api/folder/list?apikey=111111111111111": x509: certificate signed by unknown authority 
FATA[0000] Cannot read folders from premiumize.me, exiting!

**General log:**

[31mFATA[0m[0000] Cannot create downloads folder on premiumize.me, exiting! This folder already exists. 
time="2022-02-03T10:45:45+02:00" level=fatal msg="Cannot read folders from premiumize.me, exiting!"
time="2022-02-03T11:04:46+02:00" level=fatal msg="Cannot read folders from premiumize.me, exiting!"

**Comment by JackDallas** [comment]
Ah I've hit this sort of issue before in docker, give me a couple day's and I'll add a dockerfile to the project and publish to githubs docker package host

**Comment by JRDevo** [comment]
Thanks @JackDallas :)

**Comment by JRDevo** [comment]
Not sure if you know how to make an image, but these these 2 dockerfiles were handy for me.

https://github.com/linuxserver/docker-sonarr/blob/master/Dockerfile
https://github.com/linuxserver/docker-radarr/blob/master/Dockerfile

If you can replace the .yaml config with ENV variables -users can just create the container with the details rather then update the .yaml

**Comment by JackDallas** [comment]
Hey @JRDevo I've pushed up v1.0.2 and published the first docker container, I've give it a brief test, if you have any issues please comment them on issue https://github.com/JackDallas/Premiumizearr/issues/16
