### ISSUE TITLE
Raspberry Pi Support

### ISSUE THREAD

**Issue by Lloytron** [JackDallas/Premiumizearr#35]
Is it possible to add support for Raspberry Pi?

When trying to install I get the following;
Status: Downloaded newer image for ghcr.io/jackdallas/premiumizearr:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error

**Comment by JackDallas** [comment]
Hey I just pushed up docker support for armv7 and arm64, change your image to either `ghcr.io/jackdallas/premiumizearr:latest-arm64` or `ghcr.io/jackdallas/premiumizearr:latest-armv7` and let me know if it works for you :+1:

**Comment by Lloytron** [comment]
Thank you, I can confirm this worked straight away. Cheers!
