### ISSUE TITLE
Can't start Docker image

### ISSUE THREAD

**Issue by rkershenbaum** [JackDallas/Premiumizearr#38]
Here's what I'm seeing:  
`richard@Mythtv:/mnt/Media/Premiumizearr$ docker run ghcr.io/jackdallas/premiumizearr:latest /mnt/media/config.yaml:/opt/app/config.yaml \
> -v /mnt/Media/downloads:/downloads \
> -v /mnt/blackhole:/blackhole
time="2022-05-24T22:05:48Z" level=info msg="---------- Starting premiumizearr daemon ----------"
time="2022-05-24T22:05:48Z" level=info
panic: Default config created, please fill it out

goroutine 1 [running]:
github.com/jackdallas/premiumizearr/internal/config.LoadOrCreateConfig({0x0, 0x7f9889ea0998})
        /home/runner/work/Premiumizearr/Premiumizearr/internal/config/config.go:127 +0x2da
main.main()
        /home/runner/work/Premiumizearr/Premiumizearr/cmd/premiumizearrd/main.go:75 +0x50a
`
From the log:

`richard@Mythtv:/mnt/Media/Premiumizearr$ docker logs silly_merkle
time="2022-05-24T22:05:48Z" level=info msg="---------- Starting premiumizearr daemon ----------"
time="2022-05-24T22:05:48Z" level=info
panic: Default config created, please fill it out

goroutine 1 [running]:
github.com/jackdallas/premiumizearr/internal/config.LoadOrCreateConfig({0x0, 0x7f9889ea0998})
        /home/runner/work/Premiumizearr/Premiumizearr/internal/config/config.go:127 +0x2da
main.main()
        /home/runner/work/Premiumizearr/Premiumizearr/cmd/premiumizearrd/main.go:75 +0x50a
time="2022-05-24T22:09:29Z" level=info msg="---------- Starting premiumizearr daemon ----------"
time="2022-05-24T22:09:29Z" level=info
time="2022-05-24T22:09:29Z" level=info msg="Starting directory watcher..."
time="2022-05-24T22:09:30Z" level=error msg="Error getting folders: error"
time="2022-05-24T22:09:30Z" level=fatal msg="Cannot read folders from premiumize.me, exiting!"
time="2022-05-24T22:12:15Z" level=info msg="---------- Starting premiumizearr daemon ----------"
time="2022-05-24T22:12:15Z" level=info
time="2022-05-24T22:12:15Z" level=info msg="Starting directory watcher..."
time="2022-05-24T22:12:16Z" level=error msg="Error getting folders: error"
time="2022-05-24T22:12:16Z" level=fatal msg="Cannot read folders from premiumize.me, exiting!"
`

**Comment by JackDallas** [comment]
Hey, so just to clarify have you filled out the fields in `/mnt/media/config.yaml` that should have generated ?

**Comment by Lloytron** [comment]
I had this issue just now. I found that the config.yaml file was being created as a folder and not a file. I think this is a quirk of docker when mapping files that don't exist yet.

So I stopped the containers, deleted file folder and setup the file. Re ran and it found everything.

**Comment by rkershenbaum** [comment]
For me, the config.yaml was not being created at all, either as a file or a directory.

**Comment by Lloytron** [comment]
When I did this last night it made a folder called config.yaml, not a file. Apparently this is a known issue with Docker on OSX. Can you check if the same has happened to you?

I had to delete the folder and download the file directly from github and put it in the relevant folder. Might be worth editing it with your settings at this point. So try downloading this and storing it at /mnt/Media/Premiumizearr/

This is the config.yaml file; https://raw.githubusercontent.com/JackDallas/Premiumizearr/main/config.yaml

**Comment by rkershenbaum** [comment]
Ok, I created the config.yaml file at /mnt/Media/Premiumizearr/:

PremiumizemeAPIKey: [my-api-key]
`Arrs:
- Name: "Sonarr"
  URL: http://localhost:8989
  APIKey: [my-api-key]
  Type: Sonarr
- Name: "Radarr"
  URL: http://localhost:7878
  APIKey: [my-api-key]
  Type: Radarr
BlackholeDirectory: "/blackhole"
DownloadsDirectory: "/downloads"
UnzipDirectory: "/downloads"
bindIP: 192.168.1.78
bindPort: "8182"
WebRoot: "Premiumizearr"

Now when I start the container, it quickly ends with this in the logs:

time="2022-05-25T19:06:43Z" level=info msg="---------- Starting premiumizearr daemon ----------"
time="2022-05-25T19:06:43Z" level=info
time="2022-05-25T19:06:43Z" level=info msg="Starting directory watcher..."
time="2022-05-25T19:06:44Z" level=error msg="Error getting folders: error"
time="2022-05-25T19:06:44Z" level=error msg="Error getting folders: error"
time="2022-05-25T19:06:44Z" level=fatal msg="Cannot read folders from premiumize.me, exiting!"

**Comment by Lloytron** [comment]
Here is my setup, minus the keys and URLs;

I had that issue too and I can't remember what I did to get around it (I was playing at 3AM :D)

But note that my directories do not have quotation marks

PremiumizemeAPIKey: API-KEY
Arrs:
- Name: Sonarr
  URL: http://URL:8989
  APIKey: API-KEY
  Type: Sonarr
- Name: Radarr
  URL: http://URL:7878
  APIKey: API-KEY
  Type: Radarr
BlackholeDirectory: /downloads/blackhole
DownloadsDirectory: /downloads/complete
UnzipDirectory: ""
bindIP: 0.0.0.0
bindPort: "8182"
WebRoot: ""
SimultaneousDownloads: 5

**Comment by rkershenbaum** [comment]
Thanks, Lloytron.  I removed the quotes, and configured the file as your is configured, except for the location of the directories.  I'm still getting the same errors.  

I think I'm going to give up on this for now, and continue using the Premiumizer program, which works pretty well most of the time.

**Comment by JackDallas** [comment]
> Ok, I created the config.yaml file at /mnt/Media/Premiumizearr/:
> 
> PremiumizemeAPIKey: [my-api-key] `Arrs:
> 
> * Name: "Sonarr"
>   URL: http://localhost:8989
>   APIKey: [my-api-key]
>   Type: Sonarr
> * Name: "Radarr"
>   URL: http://localhost:7878
>   APIKey: [my-api-key]
>   Type: Radarr
>   BlackholeDirectory: "/blackhole"
>   DownloadsDirectory: "/downloads"
>   UnzipDirectory: "/downloads"
>   bindIP: 192.168.1.78
>   bindPort: "8182"
>   WebRoot: "Premiumizearr"
> 
> Now when I start the container, it quickly ends with this in the logs:
> 
> time="2022-05-25T19:06:43Z" level=info msg="---------- Starting premiumizearr daemon ----------" time="2022-05-25T19:06:43Z" level=info time="2022-05-25T19:06:43Z" level=info msg="Starting directory watcher..." time="2022-05-25T19:06:44Z" level=error msg="Error getting folders: error" time="2022-05-25T19:06:44Z" level=error msg="Error getting folders: error" time="2022-05-25T19:06:44Z" level=fatal msg="Cannot read folders from premiumize.me, exiting!"

This will only be because of the api key, there could be an issue reading it hmm, I'm going away today but when I'm back next week I'll try testing docker out a bit more fully, I just run it as a systemd service atm so haven't been able to fully test it

**Comment by JRDevo** [comment]
> This will only be because of the api key, there could be an issue reading it hmm, I'm going away today but when I'm back next week I'll try testing docker out a bit more fully, I just run it as a systemd service atm so haven't been able to fully test it

For docker, It may help to somehow get the variables in the .yaml mapped to the dockers environment variables, that way all the config details are passed during the creation of the container.

```
-e PremiumizemeAPIKey: xxxxxxxxx \
-e SonarrIP: localhost \ 
-e SonarrPORT:8989 \
-e SonarrAPIKey: xxxxxxxxx \
-e RadarrIP: xxxxxxxxx \
-e RadarrPORT:7878\
-e RadarrAPIKey: xxxxxxxxx \

```

Or prob best to add a dialog or window in the UI to edit the config.yaml once the web ui is up. I suspect this may be the most platform agnostic approach :)

**Comment by rkershenbaum** [comment]
I was able to start the app successfully using by the volume mapping method.

docker run \
--name Premiumizerarr \
-e PUID=1000 \
-e PGID=1000 \
-e TZ=America/Chicago \
-p 8182:8182 \
-v /mnt/Media/downloads:/downloads \
-v /mnt/Media/blackhole:/blackhole \
-v /mnt/Media/Premiumizearr/config.yaml:/opt/app/config.yaml \
ghcr.io/jackdallas/premiumizearr:latest 

That said, I agree that the best solution would be the ability to enter the parameters through the web interface.

**Comment by JackDallas** [comment]
I 100% agree, I'm gonna close this and start a disscussion here about the web ui https://github.com/JackDallas/Premiumizearr/issues/38 I'd appreciate any suggestion ya'll have :)
