### ISSUE TITLE
v1.1.6 issues in docker

### ISSUE THREAD

**Issue by JRDevo** [JackDallas/Premiumizearr#45]
I'm still getting errors if I don't mount the Data folder, or if there's no config.yaml file present when I do, however if the file is present then it works again, thanks :D

This is the log when the file isn't present; 

time="2022-06-05T22:55:00Z" level=info msg="---------- Starting premiumizearr daemon ----------"
time="2022-06-05T22:55:00Z" level=info
time="2022-06-05T22:55:00Z" level=warning msg="No config file found, created default config file"
time="2022-06-05T22:55:00Z" level=info msg="Starting web server..."
time="2022-06-05T22:55:00Z" level=info msg="Web server started on 0.0.0.0:8182"
time="2022-06-05T22:55:00Z" level=info msg="Starting directory watcher..."
time="2022-06-05T22:55:01Z" level=error msg="Error getting folders: error"
time="2022-06-05T22:55:01Z" level=error msg="Cannot read folders from premiumize.me, application will not run!"
time="2022-06-05T22:55:01Z" level=info msg="Clearing tmp directory..."
panic: Unzip directory is set to system root don't do that it will wipe your system!

goroutine 1 [running]:
github.com/jackdallas/premiumizearr/internal/service.(*DirectoryWatcherService).Start(0x400016e2e8)
	/home/runner/work/Premiumizearr/Premiumizearr/internal/service/directory_watcher_service.go:71 +0x568
main.(*App).Start(0x400016e1c0, {0x42be37, 0x4}, {0x400002801e, 0x5}, {0x400002804f, 0x5})
	/home/runner/work/Premiumizearr/Premiumizearr/cmd/premiumizearrd/app.go:105 +0x914
main.main()
	/home/runner/work/Premiumizearr/Premiumizearr/cmd/premiumizearrd/main.go:22 +0x338
time="2022-06-05T22:55:04Z" level=info msg="---------- Starting premiumizearr daemon ----------"

The test button worked well, giving errors when incorrect info was put in and confirmation when it was correct.

Another issue I noticed (btW did you want us to raise these as seperate issues or just comment here?) is that when I restart the docker container everything in my mapped download volume gets deleted.

I had mapped
      - /home/pi/Media/Downloads/:/downloads
      
 And from this I have the blackhole and completed folders as /downloads/blackhole and /doesnloads/completed
 
 But when I restart the container these folder were being deleted which was causing errors in my *Arr applications which can't then find the folders to put stuff.

_Originally posted by @Lloytron in https://github.com/JackDallas/Premiumizearr/issues/39#issuecomment-1146902158_

**Comment by JRDevo** [comment]
Same as @Lloytron, unfortunately I cant get to the web ui and the config.yaml gets reset to default if I map the yaml as a volume and the container restarts.

Mines as follows:

`sudo docker run -d   --name=Premiumizearr   -v /volumeUSB2/usbshare/config/premiumizearr/data:/data   -e PUID=1033   -e PGID=100   -e TZ=Europe/Amsterdam   -p 8182:8182   -v /volume1/Downloads:/downloads   -v /volumeUSB2/usbshare/downloads/blackhole:/blackhole   --restart unless-stopped   ghcr.io/jackdallas/premiumizearr:latest
`

Error:

```
time="2022-06-06T10:16:37Z" level=info msg="---------- Starting premiumizearr daemon ----------"
time="2022-06-06T10:16:37Z" level=info
time="2022-06-06T10:16:37Z" level=warning msg="No config file found, created default config file"
time="2022-06-06T10:16:37Z" level=info msg="Starting web server..."
time="2022-06-06T10:16:37Z" level=info msg="Web server started on 0.0.0.0:8182"
time="2022-06-06T10:16:37Z" level=info msg="Starting directory watcher..."
time="2022-06-06T10:16:37Z" level=error msg="Error getting folders: error"
time="2022-06-06T10:16:37Z" level=error msg="Cannot read folders from premiumize.me, application will not run!"
time="2022-06-06T10:16:37Z" level=info msg="Clearing tmp directory..."
panic: Unzip directory is set to system root don't do that it will wipe your system!
goroutine 1 [running]:
github.com/jackdallas/premiumizearr/internal/service.(*DirectoryWatcherService).Start(0xc0001702e8)
	/home/runner/work/Premiumizearr/Premiumizearr/internal/service/directory_watcher_service.go:71 +0x574
main.(*App).Start(0xc0001701c0, {0x8327ce, 0xc00010cf60}, {0xc00002601e, 0x5}, {0xc00002604f, 0x5})
	/home/runner/work/Premiumizearr/Premiumizearr/cmd/premiumizearrd/app.go:105 +0xa46
main.main()
	/home/runner/work/Premiumizearr/Premiumizearr/cmd/premiumizearrd/main.go:22 +0x235
```

**Comment by JRDevo** [comment]
Similarly with ghcr.io/jackdallas/premiumizearr:v1.2-rc10

**Comment by JackDallas** [comment]
Gonna close this just because these issues are added as part of the changes made in https://github.com/JackDallas/Premiumizearr/issues/39. No worries though I get where you where coming from.
