### ISSUE TITLE
Blackhole folder only scanned on startup

### ISSUE THREAD

**Issue by Lloytron** [JackDallas/Premiumizearr#46]
I've notcied that I can't get anything to successfully queue from my blackhole folder without restarting the container.

I had a few items from my *Arr programs add to the blackhole folder overnight. Premiumizearr was running and I monitored throughout the morning and it never picked them up. What is the update interval supposed to be?

I left it for 4 hours before restarting, at which point they qere picked up and queued sucessfully immediately.

As a note setting the update interval could be something also for the config page?

**Comment by JackDallas** [comment]
We don't poll the blackhole directory we set it to be "watched" and the os tells us when a file changes, I must have screwed that up when I changed the config stuff, I can see this happening on my server too I'll see about getting this fixed asap, thanks for reporting :+1:

**Comment by JackDallas** [comment]
@Lloytron Can you confirm this is still an issue, I don't actually see this happening, idk why I did before, but I'm not running docker so not sure, gonna test out the docker build tomorrow though to see if that's related

**Comment by Lloytron** [comment]
Hi, yes, this is still an issue for me, it never picks up anything in the blackhole folder unless I manually restart the container

**Comment by JackDallas** [comment]
Okay my bad I didn't have the dockerfile creating the blackhole directory 🤦 I reckon that could screw with the filesystem, could you test this pre-release for me @Lloytron https://github.com/JackDallas/Premiumizearr/releases/tag/v1.2.1-rc1 on the `dev` tag on docker :+1:

**Comment by Lloytron** [comment]
I updated to the dev tagged version and it doesn't seem to have made any difference i'm afraid.

Should I be mapping the folders individually? or just map one shared folder and use subdirectories?

**Comment by JackDallas** [comment]
Try not mounting the blackhole, having it mounted makes resuming easier after a restart if you have a long queue but try it, that could explain the issue 


Can you run with trace logging on and grab me a log over like 10 mins, add `-e PREMIUMIZEARR_LOG_LEVEL=trace`

**Comment by Lloytron** [comment]
[_premiumizearr_logs (1).txt](https://github.com/JackDallas/Premiumizearr/files/8935962/_premiumizearr_logs.1.txt)
Here are logs after running for a few minutes (I've run it for a few hours since and it just keeps repeating.

I started with nothing in the blackhole folder and then dropped a file in as it was running and left it a few minutes whilst taking these logs

**Comment by JackDallas** [comment]
@Lloytron initial rc of polling https://github.com/JackDallas/Premiumizearr/releases/tag/v1.2.2-rc1 
gonna test now on my non-docker setup

**Comment by Lloytron** [comment]
Ah lol I was wondering if I'd pulled the right version. I've enabled it in config and bingo, when I dropped something in the blackhole it found it after a while and put it into my 'Arr' folder. I saw it enter the queue OK. but now its not shown up in the downloads queue! Even after restarting?

**Comment by JackDallas** [comment]
Is it in the `arrsDownloads` folder on premiumize.me ? Because we just download whatever is in there

**Comment by JackDallas** [comment]
I know what's happening lol I changed something to add polling and didn't realise I blocked the transfer manager starting, I'll fix that and release another rc in a minute
