### ISSUE TITLE
Permission errors

### ISSUE THREAD

**Issue by Lloytron** [JackDallas/Premiumizearr#47]
I am seeing some strange errors in the logs whilst downloading;

time="2022-06-07T11:20:42Z" level=error msg="Cannot delete test.txt file in: %!(EXTRA string=/unzip)"
time="2022-06-07T11:20:42Z" level=error msg="Unzip directory not writeable: /unzip"

In this case I haven't mapped the unzip folder anywhere so it is within the container. However I get the same if it is mapped to my NAS.

Whilst downloading files are actually created in that folder.

When a file has finished downloading its giving me a permission error when unzipping to my mapped NAS drive;

time="2022-06-07T12:26:13Z" level=error msg="Could not unzip file: write /downloads/complete/[movietitle].mkv: permission denied"

I have all my clients setup using the same PGID and PUID so that they appear to be the same user and the NAS drive is fully open within my network so any user can write to it.

If I ssh into the container I can create folders and files on the same drive without any issues?

**Comment by JackDallas** [comment]
> If I ssh into the container I can create folders and files on the same drive without any issues?

That throws me off a bit. ugh annoyingly my whole setup is on a machine with no docker, I'll see if I can get a copy of sonarr and premiumizearr running on my home server in docker. The unzip directory is created in the dockerfile and should not be mounted it's supposed to be temp, I wonder if I'm missing something and need to set perms for it in the dockerfile,

**Comment by Lloytron** [comment]
> > If I ssh into the container I can create folders and files on the same drive without any issues?
> 
> That throws me off a bit. ugh annoyingly my whole setup is on a machine with no docker, I'll see if I can get a copy of sonarr and premiumizearr running on my home server in docker. The unzip directory is created in the dockerfile and should not be mounted it's supposed to be temp, I wonder if I'm missing something and need to set perms for it in the dockerfile,

Its the same if I don't mount the unzip folder and its within the container, it still says the directory is unwriteable

**Comment by JackDallas** [comment]
I'm gonna close this but if it happens again or in the future anyone ends up hitting this feel free to re-open 👍
