### ISSUE TITLE
Install Premiumizearr without root

### ISSUE THREAD

**Issue by phiivas** [JackDallas/Premiumizearr#50]
Is there any way to install Premiumizearr without root.  I am subscribed to ultra.cc seedbox, but I do not have root access there and accordingly installation of docker containers is impossible?

**Comment by JackDallas** [comment]
If you check out the latest releases the file [Premiumizearr_1.2_linux_amd64.tar.gz](https://github.com/JackDallas/Premiumizearr/releases/download/v1.2/Premiumizearr_1.2_linux_amd64.tar.gz) is a binary containing the program with all the needed assets 

You should be able to use the [install instructions](https://github.com/JackDallas/Premiumizearr#install) just drop the sudo and change the paths to be the ones you have access too

**Comment by phiivas** [comment]
Thanks,

I installed and started it successfully.  Everything works perfectly, until I terminate the shell. I will write to the support of ultra with a request to somehow make your app permanently launched.

**Comment by JackDallas** [comment]
You'll need to use screen or run it as a service using the service file provided

**Comment by phiivas** [comment]
Ok, thanks

**Comment by JackDallas** [comment]
Hey @phiivas could you follow the instructions here to generate a trace log, set this up and then leave it running ten minutes then send the log file here. Please send the file as an attachment don't copy and paste the log as it will be long, thanks

**Comment by phiivas** [comment]
So, I tried to generate a trace log with the command:

`user@server:~/.apps/Premiumizearr$ premiumizearrd -e PREMIUMIZEARR_LOG_LEVEL=trace`

the result is this:

```
user@server:~/.apps/Premiumizearr$ premiumizearrd -e PREMIUMIZEARR_LOG_LEVEL=trace
flag provided but not defined: -e
Usage of premiumizearrd:
  -config string
    	The directory the config.yml is located in (default "./")
  -log string
    	Logging level: 
    	 	info,debug,trace (default "info")
  -logging-dir string
    	The directory logs are to be written to (default "./")
```

I tried with:

`user@server:~/.apps/Premiumizearr$ premiumizearrd --log trace`

and the result is this:

```
INFO[0000] ---------- Starting premiumizearr daemon ---------- 
INFO[0000]                                              
TRAC[0000] Running load or create config                
TRAC[0000] Reading config file location from flag or env: ./ 
TRAC[0000] Trying to load config from disk              
TRAC[0000] Reading config from config.yaml              
TRAC[0000] Attempting to unmarshal config               
TRAC[0000] Config loaded, running version update        
TRAC[0000] Config loaded                                
TRAC[0000] Setting config location to ./                
TRAC[0000] Marshaling & saving config                   
TRAC[0000] Writing config to config.yaml                
TRAC[0000] Config saved                                 
INFO[0000] Cleaning unzip directory                     
TRAC[0000] Unzip directory set to: /home/phivas/downloads/Blackhole/Unzip/ 
INFO[0000] Starting web server...                       
```

I don't see a trace log file generated in the Premiumizearr folder, so it copy/paste everything from shell directly. Hopefully this will give some information.

I deleted everything from transfer on premiumize.me and now from time to time I can download.nzb and very rarely .torrent. Premiumizearr grabs 1 of 10 .torrent from the blackhole folder.

[tracelog.txt](https://github.com/JackDallas/Premiumizearr/files/8977278/tracelog.txt)

**Comment by JackDallas** [comment]
@phiivas you're using cli you need to put `--log trace`

**Comment by phiivas** [comment]
I'm sorry, maybe I'm not right or maybe you didn't read the second part of my post, but I used exactly `--log trace`

**Comment by JackDallas** [comment]
oops my fault didn't read the second part of your post, okay so we don't support .torrent files at the moment, in sonarr/radarr you can edit the download client and tick `Save Magnet Files` to only use magnet files.

If your having issues with the blackhole it's possible you're on some sort of network or virtual drive, the latest release `v1.2.2` now has a manual polling option in the config, try that out
