### ISSUE TITLE
PUID/GUID env variables ignored ? Other *arr services can't handle the folders because they are owned by root.

### ISSUE THREAD

**Issue by dabonzo** [JackDallas/Premiumizearr#52]
Docker containers from hotio or linuxsrv have the option to set PUID/GUID env variables so all of them can access mounted folders with unprivileged users.  I've tried that with premiumizearr but it seems those variables are ignored and premiuizearr downloads and saves it's config with root privileges only. Because of that, sonarr for example, can't import or delete imported episodes because it get's a permission denied.  Are you going to implement that feature anytime, so it's the same for all of the *arr containers. Or how can I mitigate that on my own ?

my docker-compose.yml excerpt with sonarr and premiumizarr only

```bash
  premiumizarr:
    container_name: premiumizearr
    image: ghcr.io/jackdallas/premiumizearr:latest
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=002
      - TZ=Europe/London
    networks:
      - the_arrs_network
    volumes:
      - ${CONFIG_FOLDER}/premiumizarr:/config
      - ${MOUNT_POINT}/premiumize/blackhole:/blackhole
      - ${MOUNT_POINT}/premiumize/downloads:/downloads
    ports:
      - 8182:8182
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr
    ports:
      - "8989:8989"
    networks:
      - the_arrs_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/sonarr:/config
      - ${MOUNT_POINT}/:/data
```

**Comment by Lloytron** [comment]
If this is the case then this would most likely explain some of the issues that I was having too

**Comment by dabonzo** [comment]
@Lloytron , yes, I saw your issue on #47 and similar issue on #50. I'll try to create a new dockerfile from hotio base and use the solution from #50. Maybe it will work

**Comment by JackDallas** [comment]
Ah see I always thought that 
```
      - PUID=1000
      - PGID=100
```
Was doing the file perms setting with the os, I'm happy to take any pull requests with dockerfile changes or even just copy the change from the code myself, I'll have a look at using hotio's base file... I think I'm still a member of their discord actually I'll see if I can get any opinions from there

**Comment by dabonzo** [comment]
I've tried with hotio for 3 hours and nothing. Linuxserver 30 minutes and everything works, permissions are right, config folder right, downloadfolders work and sonarr correctly removes after import
It's an ugly, dirty hack because after 3 hours with hotio I didn't manage to make it work. Thats why linuxserver radarr README is still displayed.
Anyway look at https://github.com/dabonzo/premiumizearr-dirtyhack

What I did:
I've used the linuxserver baseimage
I've added some stuff from Jack's dockerfile (create folders, environment variables for the config dir)
copied the application (downloaded it to the folder pr1. It's version 1.2). I'm sure that can be automated with curl or wget piped into tar, but I'm still learning. As I said, dirty dirty 
```bash
FROM ghcr.io/linuxserver/baseimage-alpine:3.15

# set version label
ARG BUILD_DATE
ARG VERSION
ARG RADARR_RELEASE
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="thelamer"

# environment settings
ARG RADARR_BRANCH="master"
ENV XDG_CONFIG_HOME="/config/xdg"
#premiumizearr env variables
ENV PREMIUMIZEARR_CONFIG_DIR_PATH=/config
ENV PREMIUMIZEARR_LOGGING_DIR_PATH=/config

#added openssl, the certificates are already installed in the baseimage
RUN \
  apk add -U --upgrade --no-cache \
    openssl

# create folders
RUN mkdir /unzip
RUN mkdir /downloads
RUN mkdir /transfers
RUN mkdir /blackhole

  
# copy local files
# manually downloaded version 1.2 of the app 
COPY pr1/premiumizearrd /opt/app/
COPY pr1/static /opt/app/static
#changes some things in root/ before
COPY root/ /
# ports and volumes
EXPOSE 8182
VOLUME /config
```

In the root folder I've changed:
```bash
#!/usr/bin/with-contenv bash

cd /opt/app/ || exit

exec \
    s6-setuidgid abc /opt/app/premiumizearrd
```

That's it
You can run it so you clone my repo
```git clone git@github.com:dabonzo/premiumizearr-dirtyhack.git``` or download the zip
In the folder with the dockerfile run ```docker build -t custom003 .```
custom003 is the name.

the docker-compose.yml (service part) should be 

```bash
  premiumizarr:
    container_name: premiumizearr
    image: custom003:latest
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=002
      - TZ=Europe/London
    networks:
      - the_arrs_network
    volumes:
      - ${CONFIG_FOLDER}/premiumizarr:/config
      - ${MOUNT_POINT}/premiumize/blackhole:/blackhole
      - ${MOUNT_POINT}/premiumize/downloads:/downloads
    ports:
      - 8182:8182
    restart: unless-stopped
```

That's what worked for me. I have no clue how to automate docker things on github or how to use versions so we can automatically download the app, so until I learn more there will probably no pull request for some time from me :). But I'll keep working

I can post the hotio-version Dockerfile and root folder. The problem there was, the app won't start (couldn't find index.html).
It has a better app-download handling though. No need to manually download the copy, it's done with curl and tar.

**Comment by JackDallas** [comment]
I just exchanged a couple messages with hotio, he's suggested away from using their base image because it's very much subject to change, I think you've got the right idea with that image though @dabonzo I think what we're looking for is an s6-overlay base image I'll take what you have and combine it with that and see if I can get something working and auto-releasing, I'll tag you and @Lloytron when that's working if you both want?

**Comment by dabonzo** [comment]
Sure. For now it works for me. And I'm also watching this repo for changes so I will be notified

**Comment by dabonzo** [comment]
@Lloytron if you need help getting it going to see if it resolves some of your issues, contact me.

**Comment by JackDallas** [comment]
@dabonzo @Lloytron If you could test out the latest dev tag and let me know if it works for you 

https://github.com/jackdallas/Premiumizearr/pkgs/container/premiumizearr/26693924?tag=v1.2.1-rc4

**Comment by dabonzo** [comment]
@JackDallas yes, seems to work for me. Does everything it should, blackhole, download, import and cleans the folders. I had to restart one time because it wouldn't show me the premiumize folder on premiumize.me but that could be an issue on my side because I can't reproduce that anymore.

**Comment by Lloytron** [comment]
Seems to be working for me too although it still  doesn't pick up any files in the blockhole folder automatically, only on the first check (or if I change the folder in settings)

I've been experimenting with Premiumizer too to see how that handled blackhole monitoring and to get that to work I have to enable their alternate method, which I think basically polls for changes at regular intervals. On that option it actually says this; "Enable when watching is not possible (for example with network file systems)"

So maybe its just not possible on my NAS setup?

**Comment by dabonzo** [comment]
Since the PUID/GUID problem is resolved with a pre-release build, I think i can close this issue. If @JackDallas  thinks it should be open, please reopen.
